### ISSUE TITLE
Lỗi pm2: command not found

### ISSUE THREAD

**Issue by quoctrung163** [roxtigger2003/mirai#10]
Mình deploy lên Glitch xài mấy bữa nay ngon lành ổn định :3
nhưng tự nhiên vào một ngày đẹp trời như hôm nay nó hiển thị lỗi :(
chi tiết như hình dưới
pm2: command not found
![Screen Shot 2020-06-12 at 13 10 26](https://user-images.githubusercontent.com/43474427/84470699-1718a700-acae-11ea-88f4-d583222cc127.png)

**Comment by quoctrung163** [comment]
mình gặp lỗi này nhiều rùi mà vẫn không biết fix sao :v, cũng thử xoá module rùi cài lại nhưng bị lỗi.
chỉ biết fork lại cái repo rùi làm lại :(

**Comment by roxtigger2003** [comment]
thử các lệnh sau:
rm -rf package-lock.json node_modules
npm cache clean --force
refresh

rồi đợi một tí xem nó có hết không

**Comment by quoctrung163** [comment]
> thử các lệnh sau:
> rm -rf package-lock.json node_modules
> npm cache clean --force
> refresh
> 
> rồi đợi một tí xem nó có hết không

**Comment by quoctrung163** [comment]
> thử các lệnh sau:
> rm -rf package-lock.json node_modules
> npm cache clean --force
> refresh
> 
> rồi đợi một tí xem nó có hết không

mình mới thử nhưng không được :v
lúc trước cũng có làm theo kiểu này :v

**Comment by roxtigger2003** [comment]
🤔 nếu thế thì phải fix được chứ nhờ

**Comment by quoctrung163** [comment]
> 🤔 nếu thế thì phải fix được chứ nhờ

![Screen Shot 2020-06-12 at 14 29 55](https://user-images.githubusercontent.com/43474427/84477073-408b0000-acb9-11ea-92ef-61114af99e86.png)

**Comment by quoctrung163** [comment]
sau refresh mình có đợi nhưng thấy vẫn bị cái pm2 :v

**Comment by roxtigger2003** [comment]
kiểm tra xem có phải hết dung lượng không "/ nghi là do nó

**Comment by quoctrung163** [comment]
> kiểm tra xem có phải hết dung lượng không "/ nghi là do nó

dung lượng vẫn ổn hết bạn :v

**Comment by quoctrung163** [comment]
mình thử npm install sau refresh thử xem :v
KQ
![Screen Shot 2020-06-12 at 14 34 24](https://user-images.githubusercontent.com/43474427/84477456-d1fa7200-acb9-11ea-8756-62cf7a9835ba.png)

**Comment by roxtigger2003** [comment]
🤔 thế xoá project đấy đi tạo cái mới, chứ chịu rồi

**Comment by roxtigger2003** [comment]
thế xoá project add lại thôi <(")

**Comment by quoctrung163** [comment]
> 🤔 thế xoá project đấy đi tạo cái mới, chứ chịu rồi
bot này bạn sử dụng, bạn deploy lên heroku hay glitch hay treo máy :v

**Comment by quoctrung163** [comment]
> thế xoá project add lại thôi <(")

cứ 2 - 3 ngày fork lại một lần :(

**Comment by roxtigger2003** [comment]
> mình thử npm install sau refresh thử xem :v
> KQ
> ![Screen Shot 2020-06-12 at 14 34 24](https://user-images.githubusercontent.com/43474427/84477456-d1fa7200-acb9-11ea-8756-62cf7a9835ba.png)

"/ nó báo hết dung lượng kia thử:
rm -rf .git xem

**Comment by quoctrung163** [comment]
![Screen Shot 2020-06-12 at 14 29 55](https://user-images.githubusercontent.com/43474427/84477860-8a281a80-acba-11ea-9fc7-2de07f9d2e2f.png)

**Comment by quoctrung163** [comment]
![Screen Shot 2020-06-12 at 14 40 11](https://user-images.githubusercontent.com/43474427/84477902-a0ce7180-acba-11ea-9c08-339d9e1b76e9.png)

**Comment by roxtigger2003** [comment]
disk 92% thế kia bruh, ```rm -rf .git``` đi bro

**Comment by quoctrung163** [comment]
> disk 92% thế kia bruh, `rm -rf .git` đi bro

mình chạy lệnh `rm -rf .git` rùi :v

**Comment by quoctrung163** [comment]
![Screen Shot 2020-06-12 at 14 43 16](https://user-images.githubusercontent.com/43474427/84478174-0f133400-acbb-11ea-95e9-39bd453324c9.png)
![Screen Shot 2020-06-12 at 14 43 35](https://user-images.githubusercontent.com/43474427/84478202-1b978c80-acbb-11ea-948f-c5ec6c622a33.png)

**Comment by roxtigger2003** [comment]
làm gì mà dung lượng cao thế "/ không fix được còn mỗi cách xoá rồi add cái mới thôi

**Comment by quoctrung163** [comment]
mình sử dụng source code bot của bạn lâu rui`, cỡ 1 tháng.
xài ngon lành được gần 3 tuần.
xong tới tuần này tự nhiên bị lỗi đó, fix ko được :v lại phải fork repo :v

**Comment by roxtigger2003** [comment]
![4A9EE41F-887A-477D-B767-44A2003D0E19](https://user-images.githubusercontent.com/36947924/84478543-b2fcdf80-acbb-11ea-95ca-fbc98620e0d7.png)
con này chạy 24/24 gần 1 tháng chưa off lần nào mà chả bị gì "/

**Comment by quoctrung163** [comment]
> ![4A9EE41F-887A-477D-B767-44A2003D0E19](https://user-images.githubusercontent.com/36947924/84478543-b2fcdf80-acbb-11ea-95ca-fbc98620e0d7.png)
> con này chạy 24/24 gần 1 tháng chưa off lần nào mà chả bị gì "/

mình có bỏ thêm code của mình nhưng bên phần handle/message.js 
chủ yếu là code lấy api thời khoá biểu hiển thị thôi :v
không biết nó có xung đột gì ko :(

**Comment by roxtigger2003** [comment]
nah, do glitch xung đột gì ấy chứ có thêm code vào thì cũng chả có gì thay đổi "/

**Comment by quoctrung163** [comment]
> nah, do glitch xung đột gì ấy chứ có thêm code vào thì cũng chả có gì thay đổi "/

chắc mình fork lại xem, đợi 2-3 ngày coi có lỗi này lại không :(

**Comment by quoctrung163** [comment]
![Screen Shot 2020-06-12 at 15 14 39](https://user-images.githubusercontent.com/43474427/84480968-92cf1f80-acbf-11ea-92ab-65054eefdb84.png)

**Comment by quoctrung163** [comment]
lúc đầu fork về không để ý, coi log nó ra thấy cái warn chỗ này :v
mà chạy vẫn được hmm
sau 2-3 ngày sau thì bị lỗi :v

**Comment by spermlord** [comment]
lỗi quá dung lượng là do bạn xóa node_module rồi install lại nhé
glitch nó sẽ ko nhận node_module ở bên ngoài /app nữa mà sẽ thẳng vào /app luôn

**Comment by KDRXD** [comment]
Và nó đã xuất hiện ._____________.
![Capture](https://user-images.githubusercontent.com/66688696/84671783-f6707b80-af51-11ea-9c37-9fc607f03697.JPG)

**Comment by KDRXD** [comment]
hôm nay em buồn......

**Comment by spermlord** [comment]
rm -rf node_modules && npm uninstall pnpm && refresh

**Comment by spermlord** [comment]
Lỗi pm2 thì chỉ có liên quan đến pnpm thôi vì nó ko get đc hết file cần có
npm uninstall pnpm && npm i pm2

**Comment by spermlord** [comment]
cách fix:
vào terminal gõ câu lệnh dưới để nó install lại
`pnpm i`
nguyên nhân: do pnpm ko tự kết nối được tới máy chủ (glitch ngu 👌🏿) nên cần phải tự làm nó install

**Comment by lequanglam** [comment]
hmm 🤔

**Comment by spermlord** [comment]
> hmm 🤔

¯\\\_(ツ)_/¯
