### ISSUE TITLE
glitch auto install package

### ISSUE THREAD

**Issue by KDRXD** [roxtigger2003/mirai#11]
Ad ơi này là update version mới hả ad?
Thỉnh thoảng em đang dùng lại thấy off xong bật log lên thấy cái đống download này
Có cách nào down hết 1 lượt ko ạ?
Chứ cứ đang dùng lại down một lần phiền quá
![IMG_20200613_114140_272](https://user-images.githubusercontent.com/66688696/84560148-42150080-ad6b-11ea-9c1a-0e18f2bccbe2.jpg)

**Comment by KDRXD** [comment]
Sau khi update cái đống kia thì bị lỗi này
Em còn chưa kịp nhập nó đã hiện ra rồi
Thậm chí còn ko gửi mã cơ
Em thử GG authenticator cũng không được nốt
Xong em tắt xác thực 2 yếu tố nó vẫn bắt nhập mã xác thực xong hiện ra cái đống xanh lè đấy :<
![15920242624328964369726380605279](https://user-images.githubusercontent.com/66688696/84560336-2579c800-ad6d-11ea-9c4b-58cf4864843f.jpg)

**Comment by quoctrung163** [comment]
> Sau khi update cái đống kia thì bị lỗi này
> Em còn chưa kịp nhập nó đã hiện ra rồi
> Thậm chí còn ko gửi mã cơ
> Em thử GG authenticator cũng không được nốt
> Xong em tắt xác thực 2 yếu tố nó vẫn bắt nhập mã xác thực xong hiện ra cái đống xanh lè đấy :<
> ![15920242624328964369726380605279](https://user-images.githubusercontent.com/66688696/84560336-2579c800-ad6d-11ea-9c4b-58cf4864843f.jpg)

cái này là do facebook bị check point
bạn vào facebook nick đó xem thử

**Comment by roxtigger2003** [comment]
> Ad ơi này là update version mới hả ad?
> Thỉnh thoảng em đang dùng lại thấy off xong bật log lên thấy cái đống download này
> Có cách nào down hết 1 lượt ko ạ?
> Chứ cứ đang dùng lại down một lần phiền quá
> ![IMG_20200613_114140_272](https://user-images.githubusercontent.com/66688696/84560148-42150080-ad6b-11ea-9c1a-0e18f2bccbe2.jpg)

cái này do package có update mới nhé kệ nó đi

**Comment by lequanglam** [comment]
bên fca-unofficial này đang có tí trục trặc về 2FA nhé, sorry

**Comment by spermlord** [comment]
> bên fca-unofficial này đang có tí trục trặc về 2FA nhé, sorry

1.2.10 vẫn dùng ngon :v

**Comment by lequanglam** [comment]
> > bên fca-unofficial này đang có tí trục trặc về 2FA nhé, sorry
> 
> 1.2.10 vẫn dùng ngon :v

vọt lên 1.3.7 rồi mà vẫn dùng bản cũ thế 🤔 update lên cho MQTT ổn định đi kìa

**Comment by spermlord** [comment]
> > > bên fca-unofficial này đang có tí trục trặc về 2FA nhé, sorry
> > 
> > 
> > 1.2.10 vẫn dùng ngon :v
> 
> vọt lên 1.3.7 rồi mà vẫn dùng bản cũ thế  update lên cho MQTT ổn định đi kìa

mấy bản gần đây toàn lỗi login nên mới dùng cũ chứ :v

**Comment by lequanglam** [comment]
> > > > bên fca-unofficial này đang có tí trục trặc về 2FA nhé, sorry
> > > 
> > > 
> > > 1.2.10 vẫn dùng ngon :v
> > 
> > vọt lên 1.3.7 rồi mà vẫn dùng bản cũ thế  update lên cho MQTT ổn định đi kìa
> 
> mấy bản gần đây toàn lỗi login nên mới dùng cũ chứ :v

nah làm quả update đi, cũng fix lỗi 2FA rồi 🤔

**Comment by spermlord** [comment]
> > > > > bên fca-unofficial này đang có tí trục trặc về 2FA nhé, sorry
> > > > 
> > > > 
> > > > 1.2.10 vẫn dùng ngon :v
> > > 
> > > 
> > > vọt lên 1.3.7 rồi mà vẫn dùng bản cũ thế  update lên cho MQTT ổn định đi kìa
> > 
> > 
> > mấy bản gần đây toàn lỗi login nên mới dùng cũ chứ :v
> 
> nah làm quả update đi, cũng fix lỗi 2FA rồi

oke, chắc mai push update lên + sleep/wake calc luôn 🤔

**Comment by spermlord** [comment]
@lequanglam 
![image](https://user-images.githubusercontent.com/37042810/84622343-f434ff80-af06-11ea-953d-970b659ec975.png)
up bản 138 bỏ dòng debug này đi bạn :v

**Comment by lequanglam** [comment]
> @lequanglam 
> ![image](https://user-images.githubusercontent.com/37042810/84622343-f434ff80-af06-11ea-953d-970b659ec975.png)
> up bản 138 bỏ dòng debug này đi bạn :v
> 

cái đấy k phải debug
mà thôi, để khi nào rảnh thêm cái tùy chọn bật cái đấy thôi (tại cần cái đó cho WebRTC extension)

**Comment by spermlord** [comment]
Glitch đã khắc phục vấn đề này 👌🏿
