### ISSUE TITLE
Lỗi Database

### ISSUE THREAD

**Issue by KDRXD** [roxtigger2003/mirai#12]
Dùng một xíu thì lại hiện ra như này 
![15923147072464114387326422057924](https://user-images.githubusercontent.com/66688696/84781716-5b3edb00-b011-11ea-8fd5-5aaa6ae7795c.jpg)
![15923147494213372831043848976293](https://user-images.githubusercontent.com/66688696/84781783-71e53200-b011-11ea-94cf-e9d0da21daa8.jpg)

**Comment by roxtigger2003** [comment]
kệ nó ông, cái này chịu vẫn chưa tìm ra

**Comment by roxtigger2003** [comment]
@spermlord

**Comment by roxtigger2003** [comment]
cơ mà bản cũ ông dùng có bị không?

**Comment by KDRXD** [comment]
> cơ mà bản cũ ông dùng có bị không?

Hình như là không 
Mấy bản gần đây mới bị bug lỗi tùm lum

**Comment by spermlord** [comment]
SQL thì chịu còn Undefined là do fca @lequanglam

**Comment by lequanglam** [comment]
> SQL thì chịu còn Undefined là do fca @lequanglam 

cái undefined thì chắc bên các ông chỉ log mỗi message chứ không log err 🤔 mà giờ tôi đang đi học nên cũng không edit để thêm tùy chọn tắt cái đó được
btw đm fb nó lâu lâu không nhận seqId?

**Comment by roxtigger2003** [comment]
**¯\_(ツ)_/¯ facebook succ**

**Comment by spermlord** [comment]
> > SQL thì chịu còn Undefined là do fca @lequanglam
> 
> cái undefined thì chắc bên các ông chỉ log mỗi message chứ không log err 🤔 mà giờ tôi đang đi học nên cũng không edit để thêm tùy chọn tắt cái đó được
> btw đm fb nó lâu lâu không nhận seqId?

¯\_(ツ)_/¯ cũng chả quan tâm lắm vì bot tôi ko bị baoh con mirai này mới bị thôi

**Comment by lequanglam** [comment]
facebook succ ¯\\_(ツ)_/¯
nó vừa làm quả 72h (nghe thằng nào đó nói có thể đá qua 092)
cay cú

**Comment by spermlord** [comment]
tôi mất 2 nick fb oan chả vì cái gì cả ¯\_(ツ)_/¯

**Comment by spermlord** [comment]
tôi mất 2 nick fb oan chả vì cái gì cả ¯\\\_(ツ)_/¯

**Comment by KDRXD** [comment]
> tôi mất 2 nick fb oan chả vì cái gì cả ¯\_(ツ)_/¯

Yep và e cũng bị checkpoint .______.

**Comment by roxtigger2003** [comment]
.__. làm cái nghề này thì chịu mất thôi xD, 4 nick đây

**Comment by roxtigger2003** [comment]
cách fix tạm:
b1: vào tools->rewind
b2: chọn mốc thời gian lùi lại 1
b3: đợi nó rewind xong

**fix tạm thôi nên nó sẽ quay lại "/**

**Comment by roxtigger2003** [comment]
lỗi database đã được sửa rồi nhé, update node lên version mới nhất nhé!
