### ISSUE TITLE
Lỗi .env

### ISSUE THREAD

**Issue by Realminicao** [roxtigger2003/mirai#14]
![Screenshot_2020-07-29-21-26-45-956_com microsoft rdc android](https://user-images.githubusercontent.com/60745960/88814067-d801cf00-d1e3-11ea-93b1-5495aea961dd.jpg)
Em cài trên VPS Windows Sever 2012 nhập lệnh .env thì bị vậy ạ
Em không biết nhiều về Code, mong ad hướng dẫn cài

**Comment by spermlord** [comment]
trên cmd thì dùng lệnh move nhé bạn

**Comment by Realminicao** [comment]
![PicsArt_07-29-10.34.02.jpg](https://user-images.githubusercontent.com/60745960/88820559-a8ef5b80-d1eb-11ea-89bf-72d3b1e64d06.jpg)
Cíu... em nhập đúng rồi mà nó bảo lỗi password

**Comment by KDRXD** [comment]
> ![PicsArt_07-29-10.34.02.jpg](https://user-images.githubusercontent.com/60745960/88820559-a8ef5b80-d1eb-11ea-89bf-72d3b1e64d06.jpg)
> Cíu... em nhập đúng rồi mà nó bảo lỗi password

Đây cũng zậy :<<<
Xài Glitch cũng y chang

**Comment by Realminicao** [comment]
Buồn ghê á

**Comment by spermlord** [comment]
email nhé

**Comment by Realminicao** [comment]
Email vẫn bị ad ợ

**Comment by roxtigger2003** [comment]
> Email vẫn bị ad ợ

nhập vào .env đúng email, mật khẩu 👌

**Comment by Realminicao** [comment]
Em sài lệnh Node Login trên Glitch lần đầu thì nó cũng bị lỗi Username/Password
Em gõ lần 2 thì lại được
Chắc chắn đây là lỗi.
Hoặc em cài thiếu gì, mong anh ra video cụ thể.

**Comment by lequanglam** [comment]
cái này có thể liên quan đến `fca-unofficial` lib nên hóng

btw ô email vẫn có thể nhập sđt và username như đăng nhập trên web thôi.

**Comment by Realminicao** [comment]
> cái này có thể liên quan đến `fca-unofficial` lib nên hóng
> 
> btw ô email vẫn có thể nhập sđt và username như đăng nhập trên web thôi.

Vậy là không cài bằng cmd được hả anh 😿

**Comment by roxtigger2003** [comment]
> Em sài lệnh Node Login trên Glitch lần đầu thì nó cũng bị lỗi Username/Password
> Em gõ lần 2 thì lại được
> Chắc chắn đây là lỗi.
> Hoặc em cài thiếu gì, mong anh ra video cụ thể.

nếu sài glitch thì sau khi nhập thông tin thì refresh lại cho nó cập nhật, còn ở local thì vẫn chưa biết nguyên nhân sao .-.

**Comment by Realminicao** [comment]
> > Em sài lệnh Node Login trên Glitch lần đầu thì nó cũng bị lỗi Username/Password
> > Em gõ lần 2 thì lại được
> > Chắc chắn đây là lỗi.
> > Hoặc em cài thiếu gì, mong anh ra video cụ thể.
> 
> nếu sài glitch thì sau khi nhập thông tin thì refresh lại cho nó cập nhật, còn ở local thì vẫn chưa biết nguyên nhân sao .-.

Em muốn chạy trên Cmd cho nó ổn định á ._. Glitch xử lý chậm hơn thì phải ._.

**Comment by spermlord** [comment]
Đã sửa lỗi trong v4.3.9
