### ISSUE TITLE
Lỗi Node Login.js

### ISSUE THREAD

**Issue by Realminicao** [roxtigger2003/mirai#15]
![Screenshot-2.png](https://user-images.githubusercontent.com/60745960/88923049-46ee2f00-d29b-11ea-8144-ff572268b429.png)
Hình như ad fix được lỗi Username/password rồi, nhưng em nhập lệnh Node login.js lại bị lỗi này ạ, có phải em cài sai cái gì không, mong ad hướng dẫn

**Comment by KDRXD** [comment]
> ![Screenshot-2.png](https://user-images.githubusercontent.com/60745960/88923049-46ee2f00-d29b-11ea-8144-ff572268b429.png)
> Hình như ad fix được lỗi Username/password rồi, nhưng em nhập lệnh Node login.js lại bị lỗi này ạ, có phải em cài sai cái gì không, mong ad hướng dẫn

Hình như nó ghi là thiếu Moudle

**Comment by KDRXD** [comment]
À nhầm module :v

**Comment by Realminicao** [comment]
> À nhầm module :v

Là sao taaaaaaa... cái này là do code hay tôi cài sai nhỉ

**Comment by spermlord** [comment]
bạn đã nhập lệnh npm install chưa?

**Comment by Realminicao** [comment]
Em quên... cảm ơn ad ạ
