### ISSUE TITLE
Lỗi lệnh Fishing

### ISSUE THREAD

**Issue by Oriental06** [roxtigger2003/mirai#16]
Từ khi bạn fix lệnh Fishing lúc trưa nay thì bây giờ mình ko dùng được lệnh Fishing nữa luôn! Mong bạn xem xét ạ

**Comment by roxtigger2003** [comment]
xin lỗi ông do rep cái issue này chậm, có vẽ bên bọn tui clean code quên check lại lỗi nên xảy ra lỗi cho cái hệ thống fishing. Hiện tui đang là người đang fix lại vui lòng ông đợi giúp

**Comment by roxtigger2003** [comment]
đã fix lỗi rồi ông nhé, cập nhật source lên version mới để tận hưởng uwu 👌
