### ISSUE TITLE
ALO ALO KO DÁM QUA BÊN ĐẤY GÁY THÌ BỌN TÔI SẴN SÀNG QUA ĐÂY CHƠI :)

### ISSUE THREAD

**Issue by hygameo** [roxtigger2003/mirai#19]

**Comment by roxtigger2003** [comment]
47/42/3 khu phố 6, hẻm 48-50 đường Bùi Quốc Khánh, phường Chánh Nghĩa, thành phố Thủ Dầu Một, Bình Dương

nhanh em ơi?

**Comment by hygameo** [comment]
căng vậy, tôi nói github mà? cần địa chỉ chi, tôi đâu muốn vô chuồng chó đâu :)

**Comment by roxtigger2003** [comment]
😏 èo tưởng thế nào, bọn khóc thuê chỉ được có nhiêu đó thôi à
