### ISSUE TITLE
chắc sợ qua đấy lắm nhỉ, bị 5 6 cái proof đè từng câu chữ thế kia thì nhục vãi ra ha :))

### ISSUE THREAD

**Issue by hygameo** [roxtigger2003/mirai#20]

**Comment by roxtigger2003** [comment]
![C2AECEDC-CC3A-44AC-8FEB-CFB53D08047C](https://user-images.githubusercontent.com/36947924/91144339-1654b600-e6de-11ea-9f6d-c2cc9726b1d2.jpeg)
![F361F461-07FB-4EAB-8026-3C4E5569211E](https://user-images.githubusercontent.com/36947924/91144343-18b71000-e6de-11ea-87ea-7365e89d1a53.jpeg)
![F226821C-9169-4C53-BFA6-5BCC021499A8](https://user-images.githubusercontent.com/36947924/91144346-19e83d00-e6de-11ea-8b91-cef0104e73a7.png)
![9CD480F1-F58F-4EA1-893F-6E3714BCE6EF](https://user-images.githubusercontent.com/36947924/91144352-1bb20080-e6de-11ea-9964-f27d59112601.jpeg)

úi zời bạn ngon đưa hết bằng chứng đây :))? hay chỉ lấy mấy cái bằng chứng giả đi hù doạ ?

**Comment by hygameo** [comment]
bằng chứng giả? giỏi thì chứng minh nó giả đi :) nhìn thực lắm đấy :) nhìn cho kỹ cái quả code xem, làm dev của rÔ bỐt tƯơNg lAi mà kiểu này trông cậy gì ây :)

**Comment by hygameo** [comment]
cần proof? 5 6 cái bên facebook kìa, spy sợ bạn nhục nên ko gửi bạn à, cần gửi lại chứ :)

**Comment by roxtigger2003** [comment]
5, 6 cái ??? bạn ơi bạn so code đi cái nào ? sao cứ mở mồm hù doạ code steal code này code nọ thế? đứng 1 chiều à :))
