### ISSUE TITLE
cho mấy câu cắn bậy vào code chắc code đẹp lắm nhỉ :)) thấy mấy bạn thích chơi kiểu đấy, thật mà nói chả khác đống rác luôn á :))

### ISSUE THREAD

**Issue by hygameo** [roxtigger2003/mirai#21]

**Comment by roxtigger2003** [comment]
thế lấy đống code rách của bạn đi dũa lại cái nết đi bạn nhé :)), "luật nhân quả không chừa được ai?" 
![38F14567-F765-48A7-8475-99E57150066F](https://user-images.githubusercontent.com/36947924/91143784-3df74e80-e6dd-11ea-9325-a91810de854b.jpeg)

**Comment by roxtigger2003** [comment]
:)) với cả chắc cái code bạn đẹp hơn cái cộng đồng hở ra rip nick facebook của bọn cấp 2 cặc chưa mở mí mắt à

**Comment by hygameo** [comment]
ơ? code rách? thế ai lại đi ôm rác vào người thế nhỉ :)), cộng đồng hở cái rip nick? sao bạn ko nghĩ đấy là luật nhân quả như bạn nói :) có lửa mới có khói, bạn ko làm gì ai rip nick bạn, giỏi thì qua đấy mà tranh luận, đảm bảo ko ai dám rip nick bạn luôn :) đụng vô đống racschi cho dơ tay vs phí thời gian chứ :)

**Comment by roxtigger2003** [comment]
bạn ơi, cái cộng đồng của bạn tôi sợ quá, "không có lửa sao có khói" thế cái cộng đồng rách của bạn đéo làm gì thì sao bọn tôi lại khịa như thế chứ? muốn biết thêm ư? hỏi cái dàn admin nít ranh của bạn đi 👌

**Comment by hygameo** [comment]
yup, bên tôi cũng có đứa kích động trc :V thôi thì xin lỗi vì mem bọn tôi kích động mấy bạn ^^, ngưng war lun nhé
