### ISSUE TITLE
Bủh

### ISSUE THREAD

**Issue by FuryCSProducer** [roxtigger2003/mirai#22]
Nào, ăn cắp code của tôi đi chứ >~<

**Comment by roxtigger2003** [comment]
![6F8B6EF8-09DA-40E9-822D-85BB9AB77F73](https://user-images.githubusercontent.com/36947924/91143547-e35df280-e6dc-11ea-80ff-66d61287cdbd.jpeg)
:)))??
![82ADE360-F700-4CE4-B0D9-A977199C70FD](https://user-images.githubusercontent.com/36947924/91143556-e6f17980-e6dc-11ea-864f-68ba5af32964.jpeg)

**Comment by roxtigger2003** [comment]
ai cơ?

**Comment by roxtigger2003** [comment]
![FB99D310-E303-4646-97C8-62B00977C0BF](https://user-images.githubusercontent.com/36947924/91144007-97f81400-e6dd-11ea-92fd-f14892b13184.jpeg)
![65049D31-E70C-4308-AFA1-93F4DFEB9ADC](https://user-images.githubusercontent.com/36947924/91144018-9a5a6e00-e6dd-11ea-8f6a-5d5d1d29351c.png)

mèo méo meo mèo meo
