### ISSUE TITLE
có 1 cái bằng chứng thì là gì?

### ISSUE THREAD

**Issue by gopnikak47** [roxtigger2003/mirai#23]
Có mỗi cái FRecognition mà cũng đòi ăn lại á thằng hèn? Sao mày không qua Facebook gáy mà chỉ núp ở đây như chó chui gầm chạn bonus thêm việc tạo fake acc thế

**Comment by roxtigger2003** [comment]
ơ thế muốn thêm? à hay thằng kia đâu rồi ấy nhỉ? nhiều tiền đi mướn khóc thuê à <(")? thế ngon qua mà gáy này mấy cháu cấp 2

**Comment by ditmec3cbruhh** [comment]
okay

**Comment by meewwmeeww** [comment]
khoan, ai vào đây thêm issue vậy?
bạn nói vậy khác đéo bạn tự sủa mình là chó

**Comment by gopnikak47** [comment]
Ngôn cãi không lại auto gán ghép cấp 2 hay chúng mày được lập trình để nói vậy nhỉ =))

**Comment by gopnikak47** [comment]
thế thằng nào cố tình gây thêm nhỉ? ![image](https://user-images.githubusercontent.com/65282158/91148688-3edfae80-e6e4-11ea-9082-23849e45fc3e.jpeg)

**Comment by gopnikak47** [comment]
hay để bố mày đạp vào mặt cho tỉnh ra? Chứ gáy ở cái GitHub này cũng đéo ai quen tâm đâu, có ngon thì qua wall bố mày gáy này mấy thằng dẩm lồn

**Comment by gopnikak47** [comment]
Forking bois go brr brr

**Comment by roxtigger2003** [comment]
welp, t không muốn bắt chính tả nhưng tiếng anh chúng mày như bọn cấp 2, chó hùa vào đây cắn đéo khác bọn con nít chưa ý thức được việc bây đang làm, còn steal code? địt mẹ mày luôn cái đống plugin chúng mày private bảo bố mày steal ? check lại code đi bọn ranh con bị dắt mũi còn hơn con chó. Đéo có lửa làm sao có khói :)

**Comment by roxtigger2003** [comment]
còn muốn tỉnh ư? 47/42/3 khu phố 6, hẻm 48-50 đường Bùi Quốc Khánh, phường Chánh Nghĩa, thành phố Thủ Dầu Một, Bình Dương

qua đây mà gáy đừng có ở nhà tưởng trên mạng muốn làm lồn gì cũng được, cháu nhé

**Comment by gopnikak47** [comment]
Thứ nhất: Tao lấy slang ra để nói đấy ý kiến gì không?
Thứ hai: Chỉ cần cái ảnh thôi, thế mày fork về làm gì? Plugins private? Bạo biện ngu quá, bọn tao để công khai và chúng mày vẫn fork về này? Bằng chứng đầy đủ gáy gáy cái địt mẹ mày. Và cái fbstate của mày làm được 6 ngày trong khi bọn tao làm trước rồi mà? Ủa, sao mày cứ gáy gáy nhấp nha nhấp nhổm trên GH làm gì thế? Lên Facebook gáy cho bàn dân thiên hạ đi chứ ranh con? ![image](https://user-images.githubusercontent.com/65282158/91157553-ad763980-e6ef-11ea-9869-65a69d8eb27a.jpeg)

**Comment by gopnikak47** [comment]
Hay không dùng slang và nói đó là tiếng Anh cấp 2? Hay user của mày, "Me is bot"?

**Comment by roxtigger2003** [comment]
ủa sao đéo khoáy cào vụ ai face đi khoáy vụ khác chi thế :)) và khóc thuê 1 bài thôi

**Comment by gopnikak47** [comment]
Ơ bố mày là co-founder bố mày không có quyền bảo vệ à. Ngố lồn vậy ranh con?

**Comment by gopnikak47** [comment]
Ai cũng có quyền đưa ra ý kiến đấy. Mày là fan Apple mày kháy Samsung tuổi lồn thì Samsung có kiện mày không? Trẻ con thế.

**Comment by roxtigger2003** [comment]
nó cũng đã nói, nó lấy về tối ưu nhưng chúng mày làm quá, bị bọn admin ranh dắt mũi vào đây khóc thuê. Thế vụ ai face tính sao :))?

**Comment by roxtigger2003** [comment]
ngưng khóc thuê đi bạn ơi càng khóc càng lòi cái ngu đấy, bọn tôi cười đủ rồi xD

**Comment by gopnikak47** [comment]
Thôi tự đem về dùng thử ^^ ![image](https://user-images.githubusercontent.com/65282158/91158523-f4b0fa00-e6f0-11ea-8337-4b194cb29008.png)

**Comment by gopnikak47** [comment]
nGưNg KhóC tHuÊ
ừ, thằng cùng làm đi bảo vệ công trình thì bị nói là khóc thuê, wow

**Comment by roxtigger2003** [comment]
:))) hộ cái tuổi? code chúng m code thế check lại date ra mắt chưa đấy? vẫn chưa hiểu à

**Comment by roxtigger2003** [comment]
vâng tôi biết co founder nào cũng muốn bảo vệ code mình, nhưng làm cái lồn gì cũng phải biết suy nghĩ. Đéo mẹ chưa kiểm tra source chưa kiểm tra ngày ra mắt bảo bọn tao steal thì lại chả bị khoáy 👍

**Comment by gopnikak47** [comment]
nó nói lúc nào thế? Tao là admin này, nãy giờ đéo có người ngoài nào nói cả, toàn admin nhé ^^

**Comment by roxtigger2003** [comment]
ừ admin, đấy tôi nói thẳng luôn đấy, biết ai steal ai đâu, ỷ ra code trước là thằng kia steal à :))

**Comment by roxtigger2003** [comment]
à nếu là admin ấy, xem lại 2 bên xem bên nào chó hùa nhiều hơn :)) rồi tinh chỉnh lại dàn admin nhé. Thân

**Comment by roxtigger2003** [comment]
còn muốn nói bọn tôi steal code các ông, ok tôi mở cái repo tester, để xem ai steal của ai?

**Comment by gopnikak47** [comment]
Nhìn c3c xem thằng mem nào chó hùa không nhé ^^ hay toàn admin bảo vệ thứ của mình?

**Comment by gopnikak47** [comment]
Ở đây nói steal code plugins cơ mà? Chứ steal code bot thì thằng nào cướp đâu?
Oh, btw, hỏi thằng Hiếu với thằng Trí xem thằng nào có hài lòng với cái cải tiến đó không nhé.

**Comment by roxtigger2003** [comment]
1/ tôi không có ý định khoáy vào source bot, source bot riêng
2/ việc steal plugin, chắc lồn gì full 100% code đó là của bọn ông thay gì tìm kiếm trên github và stackoverflow? và trong 1 lần tôi lướt thấy, ai bảo bọn tôi steal cái anime mấy ông? trong khi api đó hoàn toàn free trên mạng? lại chả không suy nghĩ trước khi bảo bọn tôi steal code các ông?

**Comment by roxtigger2003** [comment]
và việc steal tôi đính chính có cái lồn bọn tôi làm ngày làm đêm push code lên test rồi push lên source chính chứ dí buồi lấy code của mấy ông

**Comment by roxtigger2003** [comment]
trùng ý tưởng thì do các ông trùng ý tưởng hoặc có người request từ đây qua kia hoặc ngược lại, toàn bộ process code do bọn tôi lên

**Comment by gopnikak47** [comment]
![image](https://user-images.githubusercontent.com/65282158/91159837-d3e9a400-e6f2-11ea-8228-686ef04491b8.jpeg)![image](https://user-images.githubusercontent.com/65282158/91159918-f5e32680-e6f2-11ea-957a-2ab884fa5276.jpeg)

**Comment by roxtigger2003** [comment]
còn 2 thằng kia vào đây giải quyết 1 thể, bọn tôi cười đủ lắm trong tuần vừa qua rồi

**Comment by gopnikak47** [comment]
Thôi được rồi, không chửi đổng nữa, bây giờ giải quyết trong hoà bình chuyện nào ra chuyện đó đi

**Comment by roxtigger2003** [comment]
enpoint ẩn? thế nào là endpoint ẩn? enpoint anime của mấy ông có đầy trên mạng bảo ẩn ? còn vụ fbmanager tôi không dính dáng việc này ok ?

**Comment by roxtigger2003** [comment]
cái đống v2 đấy bọn tôi tìm được trên api forum, còn v3 bọn tôi có gặp gỡ qua chủ của đống api neko life

**Comment by roxtigger2003** [comment]
next: các ông kêu bọn tôi steal code? chứng minh giúp ? toàn bộ process của các ông, ngày ra mắt khi nào đủ hẳn quay lại nói bọn tôi

**Comment by roxtigger2003** [comment]
còn mấy cái commit dạo gần đây thì do tôi có hơi thái quá trong phần này, việc các ông bảo bọn tôi steal code này steal nọ ai chả tức?

**Comment by gopnikak47** [comment]
Rồi, thế ý các ông là các ông không steal code của chúng nó chứ gì?

**Comment by roxtigger2003** [comment]
tất nhiên là thế, trùng ý tưởng nhưng chả trùng process của code? code thì thiếu gì chỗ tham khảo chẳng hạn github này?

**Comment by roxtigger2003** [comment]
còn khăng khăng bọn tôi steal thì xin mời, bọn tôi làm đúng thì sợ buồi gì ?

**Comment by gopnikak47** [comment]
rồi ok, chuyện này tôi cũng thái quá khi mấy ông push mấy cái commit này, bonus quả treo địa chỉ nhà ông khắp cái internet 
nhưng mà tôi cũng có lỗi trong chuyện này, nhưng từ sau nói cho các ông biết nhé, việc dùng slang và một số hành động thái quá không nói lên được người nói là ai đâu. Chuyện các ông nói tôi là trẻ cấp 2 thì nó cũng tương đối buồn cười rồi đấy
Còn bây giờ chúng tôi sẽ gọi Hiếu với Trí ra giải quyết thẳng, cảm ơn

**Comment by roxtigger2003** [comment]
đấy thế cho nhanh không? mấy ông cứ khăng khăng bọn tôi steal nửa buồn nửa cười thật

**Comment by FuryCSProducer** [comment]
ừ, cái vụ neko tôi có hơi rage thật, lại còn ông spy kia nói đã test nên tôi mới rage, tôi xin lỗi ông

**Comment by roxtigger2003** [comment]
cái đống fork từ fbmanager bọn tôi cũng không biết bọn nó có làm, nên tôi cũng không hiểu rõ tại sao mấy ông có thể đổ vào được

**Comment by roxtigger2003** [comment]
còn cái fbappstate thì bọn tôi đúng là có fork về làm gọn lại code nhưng mấy ông thái quá nên bọn tôi chịu, tôi cũng bị dính do spermlord

**Comment by FuryCSProducer** [comment]
thế thì trách thanh niên kia đi :)))

**Comment by roxtigger2003** [comment]
welp như đã nói ở trên, bọn tôi chỉ có ý định pull về rút gọn code không có ý gì cả, nếu là author của code thì các ông có quyền gỡ source, còn bên đây ai cũng biết cái sai rồi "/

**Comment by roxtigger2003** [comment]
còn thắng với trí, vào đây làm việc nốt cho nó xong đi

**Comment by gopnikak47** [comment]
Oh btw, bảo Mirai users là đừng leak tin nhắn của các box C3C đi, kẻo lại có ông nào chê rồi leak và lại xảy ra chuyện ^^

**Comment by gopnikak47** [comment]
Thông báo trước là chúng tôi gỡ các bài có tính chất gây war rồi nhé, đề nghị gỡ dòng đbrr đi ^^ cảm ơn

**Comment by gopnikak47** [comment]
Và sau đợt này thì Mirai với C3C không có can dự gì nhau nhé, mấy ông cũng nên làm thông báo được rồi đó.

**Comment by roxtigger2003** [comment]
> Oh btw, bảo Mirai users là đừng leak tin nhắn của các box C3C đi, kẻo lại có ông nào chê rồi leak và lại xảy ra chuyện ^^

vụ này bọn tôi cố thôi

**Comment by gopnikak47** [comment]
ừ, họ qua chơi rồi tham khảo cũng được, nhưng chuyện cap tin nhắn mấy bạn dùng c3c rồi leak qua Mirai rồi gây ra xích mích thì nó không vui đâu
Nói gì thì nói, chúc bên ông phát triển và không bị flop 😀

**Comment by roxtigger2003** [comment]
![0CE6E05E-6369-4994-AA4D-10B5DDB3F02F](https://user-images.githubusercontent.com/36947924/91164464-3f367480-e6f9-11ea-97b0-842dab303bde.png)
🤔 cái vụ cap tôi nói với bọn nó rồi, còn nghe hay không thì bọn tôi chịu đông quá quản không hết

**Comment by Kaysil** [comment]
> còn thắng với trí, vào đây làm việc nốt cho nó xong đi

đây

**Comment by gopnikak47** [comment]
rồi ok cảm ơn, bây giờ không ai liên quan đến ai nhé.

**Comment by roxtigger2003** [comment]
> > còn thắng với trí, vào đây làm việc nốt cho nó xong đi
> 
> đây
thế ý ông bây giờ thế nào?

**Comment by Kaysil** [comment]
tôi thì như nào cũng được

**Comment by roxtigger2003** [comment]
ok thế này, nhưng đã nói ở trên, bọn tôi xin khẳng định việc steal code từ plugin của các ông là không có. Đến cả tôi cũng chả biết các ông ở phương trời nào. Việc trùng code hoặc trùng process cũng có thể là do kham thảo từ một nguồn hoặc cùng chung ý nghĩ của bọn tôi dựng lên từ bảng. Cái này tôi không chắc, nhưng cũng có thể bọn bên tester của bọn tôi có thể đã mượn ý tưởng từ bên các ông và gửi cho bộ phận coder(tôi và Nghĩa) làm nên tôi cũng không biết nguồn gốc cái request đó có phải từ chính bọn nó nghĩ ra hay đi mượn ý tưởng

**Comment by gopnikak47** [comment]
ok

**Comment by roxtigger2003** [comment]
tôi chỉ có nhiêu đó thôi ¯\_(ツ)_/¯

**Comment by Kaysil** [comment]
ok

**Comment by gopnikak47** [comment]
mmhm, vậy thì bây giờ C3C và Mirai chính thức làm lành nhé.

**Comment by roxtigger2003** [comment]
thì đấy tôi cũng đã phát thông báo cũng như recover code rồi

**Comment by gopnikak47** [comment]
ok, done, close issue đi

**Comment by roxtigger2003** [comment]
welp đến thế thôi, mong mấy ông gỡ bài cũng như xem chuyện này chưa tồn tại nhé 
#fromMiraiwithLove
