### ISSUE TITLE
hmmm... các ông gọi bọn tôi là bọn nhóc cấp 2? thế các ông nên nhìn lại những từ ngữ các ông dùng chứ nhỉ, fact chỉ có đúng đc cái vụ stolen của fury, mà có khi còn sai fact đấy nữa cơ chứ :)) toàn dùng từ địt mẹ với đbrr? giống bọn cấp 2 đi chửi lộn nhỉ :)

### ISSUE THREAD

**Issue by hygameo** [roxtigger2003/mirai#24]

**Comment by roxtigger2003** [comment]
thế bọn ông khác đéo gì stolen code trên stack lẫn module rồi dí buồi nhận :))? với cả lại chả là toàn bọn cấp 2 không biết đầu đuôi câu chuyện bị dắt mũi khóc thuê giúp bọn nó? đéo cần phải hỏi khóc thuê ở đâu cả check lại cái issue của cái project này đi :)). Sai fact? đi steal toàn bộ source code người ta nguồn thì đéo bảo sai thì là cái lồn gì? cái fbappstate bọn tôi lấy về rút gọn lại cũng bảo steal đấy thôi? xem lại đi bọn nào là cấp 2 bị dắt mũi còn hơn con chó :))))))

**Comment by hygameo** [comment]
trên đấy họ share mà? có bản quyền gì đâu? còn ở đây, những đoạn code trong proof là đều bên bọn tôi tự làm? các ông steal như đúng rồi đấy thôi, còn nếu nói về vụ open source, thì ông cũng đi chửi bọn tôi steal code ông đấy :)) tự vả mạnh thật. ban đầu bọn tôi cũng chả làm quá lên, chính các ông khơi mào vụ steal trc đấy thôi :)), tôi cấp 2 đấy, nói chuyện cho giống đàn anh xíu đi nào, chứ nói chuyện kiểu đấy ông cũng chả hơn tôi nhiêu đâu nhé. về cái fact, bọn tôi chỉ là copy paste vs cả đâu phải toàn bộ? bọn tôi cũng đã chỉnh sửa ít nhiều trong đấy để phù hợp vs nhu cầu mà? ừ thì vụ fbappstate đúng thật :V bị dắt mũi? ý ông là tôi đi khóc thuê cho dàn ad bên c3c à :V

**Comment by roxtigger2003** [comment]
steal ? ông cho rằng nó là ****

**Comment by roxtigger2003** [comment]
2/ toàn bộ code của bọn tôi được đóng góp qua request và bọn tôi tự làm, dí buồi lồn gì lấy code mấy ông mà đắp vào? và đây là facebook chắc chắn ý tưởng trùng nhau nhưng chắc lồn gì cách bố trí các process giống :))?

**Comment by hygameo** [comment]
nah, ok, ông cúng, cũng ko thể nói do code giống thì steal đc, xin lỗi =D thôi thì dàn admin cũng ngưng war rồi, nên tôi cũng thế ây ^^
