### ISSUE TITLE
Deploy lên heroku

### ISSUE THREAD

**Issue by LingKMA** [roxtigger2003/mirai#6]
Update file app.json config thêm các biến môi trường

**Comment by roxtigger2003** [comment]
ok, bên bọn tôi sẽ làm vụ heroku sau nha ^w^

**Comment by spermlord** [comment]
hình như deploy lên heroku thì nó sẽ không cho write file vào dyno đấy nữa. mình cũng không rõ lắm về vấn đề này (vì ít khi dùng heroku) và đang tìm cách giải quyết, nếu bạn có cách giải quyết thì hãy comment vào issue này luôn nhé ♥

**Comment by lequanglam** [comment]
heroku chỉ giữ file được ghi thêm chỉ khi còn hoạt động thôi, bị down phát là mất file luôn

**Comment by spermlord** [comment]
vậy thì lúc uptime down hoặc update bản mới là mất hết dữ liệu .-.
có vẻ mình sẽ phải viết lại 1 bản hỗ trợ addon của heroku rồi ;-;

**Comment by lequanglam** [comment]
1-click deploy lên heroku công nhận khó làm lắm .-.

**Comment by spermlord** [comment]
chắc nếu deploy lên heroku thì phải làm 1 file js để check xem có đang dùng heroku không, và nếu dùng thì cài những thứ cần thiết 🤔?

**Comment by roxtigger2003** [comment]
🤔 hoặc là bỏ luôn vụ heroku sài mỗi bên glitch với local thôi

**Comment by lequanglam** [comment]
hoặc tạo 1 service để upload/download config mỗi lần phát hiện chạy trên heroku? 🤔 có thể dùng app name hoặc cái gì đó để check chẳng hạn

**Comment by roxtigger2003** [comment]
> nhường lại cho tâm 👌🏿
> too lazy to do

j bruh

**Comment by KDRXD** [comment]
> nhường lại cho tâm 👌🏿
> too lazy to do

Nước đi hay đấy ( ͡° ͜ʖ ͡°)

**Comment by spermlord** [comment]
> > nhường lại cho tâm 👌🏿
> > too lazy to do
> 
> j bruh

Cố làm đi để nâng trình code lên =))
t lười lắm r

**Comment by spermlord** [comment]
Deploy Heroku sẽ để khi nào mình test được code đã nhé
Tạm thời close issue này
