### ISSUE TITLE
Thêm API

### ISSUE THREAD

**Issue by KDRXD** [roxtigger2003/mirai#7]
Ad có thể thêm API tính giờ đi ngủ được không ạ :V

**Comment by KDRXD** [comment]
À còn lệnh !đấm em không thấy gì cả :<
Có mỗi !slap hơi chán :)))
Thêm kick với smash thì tuyệt vời

**Comment by spermlord** [comment]
> À còn lệnh !đấm em không thấy gì cả :<
> Có mỗi !slap hơi chán :)))
> Thêm kick với smash thì tuyệt vời

Lệnh đấm bạn có thể vào message.js rồi copy tát và edit nó nhé 👌🏿

**Comment by KDRXD** [comment]
Ơ nhưng mà  cái api để lấy gif đấm thì lấy như thế nào ạ?
Em thấy có dòng return request('https://nekos.life/api/v2/img/slap') nhưng mà search link đấy trên Google không ra :V
Api đấm không lẽ lại là nekos.life/api/v2/smash :Đ??

**Comment by roxtigger2003** [comment]
> Ơ nhưng mà cái api để lấy gif đấm thì lấy như thế nào ạ?
> Em thấy có dòng return request('https://nekos.life/api/v2/img/slap') nhưng mà search link đấy trên Google không ra :V
> Api đấm không lẽ lại là nekos.life/api/v2/smash :Đ??

đấm thì chả có đâu 🤔

**Comment by KDRXD** [comment]
> > Ơ nhưng mà cái api để lấy gif đấm thì lấy như thế nào ạ?
> > Em thấy có dòng return request('https://nekos.life/api/v2/img/slap') nhưng mà search link đấy trên Google không ra :V
> > Api đấm không lẽ lại là nekos.life/api/v2/smash :Đ??
> 
> đấm thì chả có đâu

Em cũng vừa tìm xong vô phần api cx ko thấy đấm :V

**Comment by KDRXD** [comment]
Có cái api OwOify trông cũng hay hay nhưng em không biết làm :((((

**Comment by lequanglam** [comment]
> Có cái api OwOify trông cũng hay hay nhưng em không biết làm :((((

đâu đâu hóng

**Comment by KDRXD** [comment]
Cái api https://nekos.life/api/v2/owoify ý nhưng không biết làm kiểu gì :V

**Comment by spermlord** [comment]
![20200614_235011](https://user-images.githubusercontent.com/37042810/84599136-fd3bb780-ae99-11ea-9478-7ac6dd2400f2.jpg)
![20200614_235051](https://user-images.githubusercontent.com/37042810/84599138-ff9e1180-ae99-11ea-88f9-ed7834aa1f62.jpg)
![20200614_235116](https://user-images.githubusercontent.com/37042810/84599140-0036a800-ae9a-11ea-869a-dcf8b549f542.jpg)
Nhá hàng tí :))

**Comment by KDRXD** [comment]
> ![20200614_235011](https://user-images.githubusercontent.com/37042810/84599136-fd3bb780-ae99-11ea-9478-7ac6dd2400f2.jpg)
> ![20200614_235051](https://user-images.githubusercontent.com/37042810/84599138-ff9e1180-ae99-11ea-88f9-ed7834aa1f62.jpg)
> ![20200614_235116](https://user-images.githubusercontent.com/37042810/84599140-0036a800-ae9a-11ea-869a-dcf8b549f542.jpg)
> Nhá hàng tí :))

Uầy 
Nice :Đ

**Comment by KDRXD** [comment]
> ![20200614_235011](https://user-images.githubusercontent.com/37042810/84599136-fd3bb780-ae99-11ea-9478-7ac6dd2400f2.jpg)
> ![20200614_235051](https://user-images.githubusercontent.com/37042810/84599138-ff9e1180-ae99-11ea-88f9-ed7834aa1f62.jpg)
> ![20200614_235116](https://user-images.githubusercontent.com/37042810/84599140-0036a800-ae9a-11ea-869a-dcf8b549f542.jpg)
> Nhá hàng tí :))

Ơ thế ad định lúc nào update đấy :)?
Chờ mòn mông zồi

**Comment by lequanglam** [comment]
> ![20200614_235011](https://user-images.githubusercontent.com/37042810/84599136-fd3bb780-ae99-11ea-9478-7ac6dd2400f2.jpg)
> ![20200614_235051](https://user-images.githubusercontent.com/37042810/84599138-ff9e1180-ae99-11ea-88f9-ed7834aa1f62.jpg)
> ![20200614_235116](https://user-images.githubusercontent.com/37042810/84599140-0036a800-ae9a-11ea-869a-dcf8b549f542.jpg)
> Nhá hàng tí :))

hả, copy time 🤔

**Comment by roxtigger2003** [comment]
🤔🤔

**Comment by spermlord** [comment]
> > ![20200614_235011](https://user-images.githubusercontent.com/37042810/84599136-fd3bb780-ae99-11ea-9478-7ac6dd2400f2.jpg)
> > ![20200614_235051](https://user-images.githubusercontent.com/37042810/84599138-ff9e1180-ae99-11ea-88f9-ed7834aa1f62.jpg)
> > ![20200614_235116](https://user-images.githubusercontent.com/37042810/84599140-0036a800-ae9a-11ea-869a-dcf8b549f542.jpg)
> > Nhá hàng tí :))
> 
> hả, copy time

Original vl luôn nhé, tôi còn ko bt bot của ông là gì cơ =))

**Comment by lequanglam** [comment]
> Original vl luôn nhé, tôi còn ko bt bot của ông là gì cơ =))
> Ngồi fix cái moment muốn mệt gần chết ._.

oc mà đâu nói gì đâu 🤔 ý tôi là cho tôi xin cái idea lmao

**Comment by spermlord** [comment]
> > Original vl luôn nhé, tôi còn ko bt bot của ông là gì cơ =))
> > Ngồi fix cái moment muốn mệt gần chết ._.
> 
> oc mà đâu nói gì đâu  ý tôi là cho tôi xin cái idea lmao

có code trong msg.js rồi đó ông, steal đi :))

**Comment by roxtigger2003** [comment]
j steal <(")

**Comment by lequanglam** [comment]
> Có cái api OwOify trông cũng hay hay nhưng em không biết làm :((((

bump, giờ mới mò ra cách dùng api đó, sau 24 FUCKING DAYS :))
![image](https://user-images.githubusercontent.com/29724654/86516574-f3c7be80-be4b-11ea-84bd-fff348241fae.png)

**Comment by KDRXD** [comment]
> > Có cái api OwOify trông cũng hay hay nhưng em không biết làm :((((
> 
> bump, giờ mới mò ra cách dùng api đó, sau 24 FUCKING DAYS :))
> ![image](https://user-images.githubusercontent.com/29724654/86516574-f3c7be80-be4b-11ea-84bd-fff348241fae.png)

Ồh zia :>
Thế sau bao nhiu fuckin day nữa ad mới nàm xong O w O?
