### ISSUE TITLE
Lỗi Lệnh setmoney

### ISSUE THREAD

**Issue by KDRXD** [roxtigger2003/mirai#9]
Khi setmoney me hoặc người khác đã báo thành công nhưng khi "kẹt ngân" thì lại thành "null' đô -> setmoney lại lần 2 báo User không tồn tại trong dữ liệu

**Comment by roxtigger2003** [comment]
okay bọn tôi sẽ làm lại phần setmoney sau 🤔

**Comment by spermlord** [comment]
mô tả rõ lỗi đc ko bạn

**Comment by KDRXD** [comment]
> mô tả rõ lỗi đc ko bạn

Dạ đây ạ
https://drive.google.com/file/d/1rTIdZE_DGmmrM-0-VtmhbvIZHia1vDeo/view?usp=sharing
https://drive.google.com/file/d/1rRVDQm_LX61ryJ3ohuWkKV9-AFyaiuKV/view?usp=sharing
tại git không cho up video nên e up tạm link GG Drive :V

**Comment by spermlord** [comment]
> > mô tả rõ lỗi đc ko bạn
> 
> Dạ đây ạ
> https://drive.google.com/file/d/1rTIdZE_DGmmrM-0-VtmhbvIZHia1vDeo/view?usp=sharing
> https://drive.google.com/file/d/1rRVDQm_LX61ryJ3ohuWkKV9-AFyaiuKV/view?usp=sharing
> tại git không cho up video nên e up tạm link GG Drive :V

Đã fix, tối nay sẽ update 👌🏿

**Comment by spermlord** [comment]
![Screenshot_20200618-135847_Messenger](https://user-images.githubusercontent.com/37042810/84988265-e92ed900-b16b-11ea-94ba-c430e63793ee.jpg)

Code vẫn bth nhé
